### ISSUE TITLE
Crittr should terminate command line process when it fails

### ISSUE THREAD

**Issue by teles** [hummal/crittr#10]
**Is your feature request related to a problem? Please describe.**
I'm using crittr to generate critical css for deployment. The deployment process follows these steps:

*     grunt _partial_dev_local_before_critical --env="$env" --compress_js=true
*     node ./crittr.js # its the Critrr running
*     grunt _partial_dev_local_after_critical_for_deploy

The problem:

Sometimes Crittr fails to generate critical css and the deployment continues.
In this case I would like to make sure that the deployment will fail if the critical css is not properly generated.

**Describe the solution you'd like**

I would like to have an option to make Crittr terminate command line process if it fails.

**Comment by hummal** [comment]
Thanks for sharing. 
Can you provide an error message occuring in your case? Means: why is the css not properly generated?

**Comment by teles** [comment]
Hi, i just solved this problem calling an `exit(1)` if generated critical fails.
