### ISSUE TITLE
Leaving css empty should use site css

### ISSUE THREAD

**Issue by hummal** [hummal/crittr#23]
**Describe the solution you'd like**
When Iam not using the css property I would like crittr to use the websites css

**Describe alternatives you've considered**
Using only the css property makes it more complex for basic users without heavy performance lifting

**Comment by timonbandit** [comment]
@hummal #25 Should fix the problem I guess.

**Comment by hummal** [comment]
Done in version 1.4.0. Thanks @timonbandit for helping
