### ISSUE TITLE
Instances of puppetter not getting closed/killed

### ISSUE THREAD

**Issue by Creativico** [hummal/crittr#43]
**Description**:
Really simple, if you run many site urls through crittr within a span of few seconds you will get a bunch of puppetter processes open as they don't close.

https://jumpshare.com/v/017bMHfJYHkz1OBqCkmd

** How to reproduce the issue? **
I'm running 50 site urls per minute (approx) and after few minutes crittr processes keep hanging and clog up the server.

**Expected behavior**
Processes should die when the script ends

**Screenshots**
https://jumpshare.com/v/017bMHfJYHkz1OBqCkmd

**Comment by hummal** [comment]
False positive?

**Comment by Creativico** [comment]
Sorry, just took a look on different VPS and it's not producing the issue so far.  I'm monitoring but seems everything is identical (version of OS, components..) but the issue does not repeat. So I closed until I verify on new VPS instances.
